metric: RBOX
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: annotations\annotations_train.json
  dataset_dir: D:\PhD\Data per camp\DetectionDataset\Identification-split\coco-dataset
  data_fields: ["image", "gt_bbox", "gt_class", "is_crowd", "gt_poly"]
  allow_empty: true
  empty_ratio: 0.05

EvalDataset:
  name: COCODataSet
  image_dir: val
  anno_path: annotations\annotations_val.json
  dataset_dir: D:\PhD\Data per camp\DetectionDataset\Identification-split\coco-dataset
  data_fields: ["image", "gt_bbox", "gt_class", "is_crowd", "gt_poly"]
  allow_empty: true
  empty_ratio: 1.

TestDataset:
  name: COCODataSet
  image_dir: test
  anno_path: annotations\annotations_test.json
  dataset_dir: D:\PhD\Data per camp\DetectionDataset\Identification-split\coco-dataset
  allow_empty: true
  empty_ratio: 1.
