_BASE_: [
  'ppyoloe_plus_sod_crn_l_80e_visdrone.yml',
]
# log_iter: 100
# snapshot_epoch: 10
weights: output/ppyoloe_plus_sod_crn_l_largesize_80e_visdrone/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_l_80e_coco.pdparams

PPYOLOEHead:
  reg_range: [-2,20]
  static_assigner_epoch: -1

