_BASE_: [
  'coco_identification.yml',
  'runtime.yml',
  'optimizer_80e.yml',
  'ppyoloe_plus_crn.yml',
  'ppyoloe_plus_reader.yml'
]


weights: output/ppyoloe_plus_sod_crn_l_largesize_80e_visdrone/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_l_80e_coco.pdparams

depth_mult: 1.0
width_mult: 1.0

CustomCSPPAN:
  num_layers: 4
  use_trans: True

PPYOLOEHead:
  reg_range: [-2,20]
  static_assigner_epoch: -1
  static_assigner:
    name: ATSSAssigner
    topk: 9
  assigner:
    name: TaskAlignedAssigner_CR
    center_radius: 1
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 10000
    keep_top_k: 500
    score_threshold: 0.01
    nms_threshold: 0.6


