_BASE_: [
  'dota_ms.yml',
  'runtime.yml',
  'optimizer_3x.yml',
  'ppyoloe_r_reader.yml',
  'ppyoloe_r_crn.yml'
]

# log_iter: 50
# snapshot_epoch: 1
weights: output/ppyoloe_r_crn_x_3x_dota/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_x_pretrained.pdparams
depth_mult: 1.33
width_mult: 1.25
