worker_num: 8
eval_height: &eval_height 800
eval_width: &eval_width 800
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomRRotate: {angle: [-45,45], angle_mode: "range", scale_mode: "range", scale: [0.5, 1.5], rotate_prob: 0.7 }
    - RandomDistort: {hue: [-5, 5, 0.5],contrast: [0.5, 1.5, 0.5], saturation: [0.5, 1.5, 0.5], brightness: [0.5, 1.5, 0.5], prob: 0.2}
    - RandomRFlip: {prob: 0.5}
    - Mosaic: {prob: 0.2, input_dim: *eval_size, enable_mixup: false, scale: 1.0 }
  batch_transforms:
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
    - PadGT: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 8

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 8
