# env_file: .env

services:

  minio:
    image: "minio/minio:RELEASE.2025-04-22T22-12-26Z"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  labelstudio:
    image: "heartexlabs/label-studio:20250507.142758-develop-2e2c7ed2f"
    ports:
      - "8080:8080"
    volumes:
      - labelstudio_data:/label-studio/data
    depends_on:
      - minio

  # PostgreSQL database
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mlflowdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  mlflow_service:
    build:
      context: ./mlflow_service        # directory containing your Dockerfile
      dockerfile: Dockerfile           # omit if it’s literally named “Dockerfile”
    image: mlflow_service:latest
    environment:
      BACKEND_STORE_URI: sqlite:///mlflow.db
      DEFAULT_ARTIFACT_ROOT: s3://mlflow-artifacts
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    ports:
      - "5000:5000"                     # expose MLflow UI/API on port 5000
    volumes:
      - mlflow_service_data:/mlflow   # persist mlruns metadata
    depends_on:
      - minio

  # inference:
  #   build:
  #     context: ./inference_service
  #     dockerfile: Dockerfile
  #   image: inference:latest
  #   ports:
  #     - "4141:4141"
  #   volumes:
  #     - inference_service_data:/model_weights
  #   depends_on:
  #     - minio

  dashboard:
    build:
      context: ./dashboard_service
      dockerfile: Dockerfile
    image: dashboard:latest
    ports:
      - "8501:8501"
    volumes:
      - dashboard_service_data:/inference_results



volumes:
  minio_data:
  labelstudio_data:
  mlflow_service_data:
  dashboard_service_data:
  inference_service_data:
  postgres_data:
