name: CI with uv
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.ipynb"
      - "**.cff"

  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.ipynb"
      - "**.cff"

  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day

  workflow_dispatch: # allow running sync via github ui button

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv python package manager
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - run: uv python install 3.11
      - name: Format codebase
      - run: uvx format .
