# dataset root dir
path: D:\PhD\Data per camp\DetectionDataset

train:
  - Rep 1\train\images

val:
  - Rep 2\val\images
  - Rep 1\val\images

# test:  # test images (optional)

# Classes
nc: 1 # number of classes
names:
  0: wildlife
